FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential tzdata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_test.txt .
RUN pip install --no-cache-dir -r requirements_test.txt

COPY . .

CMD ["pytest", "--tb=short", "-v"]
